[functions]
  included_files = [
    "node_modules/.prisma/client/schema.prisma",
    "node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node",
    "node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node"
  ]

[build]
  command = "npm run build"
  publish = ".next"
